version: '3.5'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - database

  symfony:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
    restart: always

  database:
    # In production, you may want to use a managed database service
    image: mysql:5.7

  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
