version: '3.5'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - postgres

  symfony:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
    restart: always

  postgres:
    # In production, you may want to use a managed database service
    image: postgres:9.6-alpine

  adminer:
    image: adminer
    depends_on:
      - postgres
    restart: always
