version: '3.5'

services:
  php:
    container_name: mybonjob_local_php
    networks:
    - mybonjob_local
    environment:
    - WITH_XDEBUG=true
    volumes:
    - ./symfony:/var/www/symfony:rw,cached

  symfony:
    container_name: mybonjob_local_symfony
    networks:
    - mybonjob_local
    ports:
    - "8101:443"
    volumes:
    - ./symfony/public:/var/www/symfony/public:ro

  postgres:
    container_name: mybonjob_local_postgres
    networks:
    - mybonjob_local
    environment:
    - POSTGRES_DB=onerba
    - POSTGRES_USER=onerba
    - POSTGRES_PASSWORD=zn2vh49sgq4ni76564s4
    - PGDATA=/var/lib/postgresql/data/db-files/
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  adminer:
    container_name: mybonjob_local_adminer
    networks:
    - mybonjob_local
    ports:
    - 2021:8080

  mailcatcher:
    build:
      context: ./symfony
      dockerfile: docker/mailcatcher/Dockerfile
    container_name: mybonjob_local_mailcatcher
    networks:
    - mybonjob_local
    ports:
    - 1026:1026
    - 1081:1081

networks:
  mybonjob_local:
    name: mybonjob_local
