version: '3.5'

services:
  php:
    container_name: mybonjob_php
    volumes:
      - ./symfony:/var/www/symfony:rw,cached

  symfony:
    container_name: mybonjob_local_symfony
    ports:
      - "8101:443"
    volumes:
      - ./symfony/public:/var/www/symfony/public:ro

  database:
    container_name: mybonjob_mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=mybonjob
      - MYSQL_USER=mybonjob
      - MYSQL_PASSWORD=X0145Hmybonjob
      - MYSQL_ROOT_PASSWORD=R0145mybonjob
      - TZ=Europe/Paris
    #volumes:
    #  - ./mysql-data/data:/var/lib/mysql:rw
    #  - ./mysql-data/dumps:/var/dumps:rw
    #  - ./mysql-data/sessions/mysql:/root:rw
    expose:
      - "3306"

  adminer:
    container_name: mybonjob_adminer
    ports:
      - 2021:8080

networks:
  default: # this network
    driver: bridge
